// Scenario 2 + 4: person with no finding, holes > 0 -> strip opens attempts directly; Escape/X focus; narrow; held-stricter play
const L = require('./lib.cjs')
const [person = 'Arun', app = 'AWS Console', tag = 's2'] = process.argv.slice(2)
const O = L.OUT + tag + '-'
;(async () => {
  const { browser, page, errors } = await L.open()
  await L.toChecks(page)
  await L.fillAndRun(page, person, app)
  const outcome = page.locator('[data-node="outcome"]').first()
  await outcome.scrollIntoViewIfNeeded()
  await outcome.screenshot({ path: O + '01-outcome.png' })
  const strip = page.locator('button.tj-hero__strip')
  console.log('strip', await strip.count(), (await strip.allTextContents()).join(' | '))
  console.log('strip aria', await strip.first().evaluate((b) => [b.getAttribute('aria-expanded'), b.getAttribute('aria-controls')]).catch(() => 'none'))
  console.log('why? btn', await page.locator('.tj-hero__whybtn').count(), 'quiet link', await page.locator('.tj-hero__attempts').count())
  console.log('chain overlaps', JSON.stringify(await L.overlaps(page, '.tj-chain')))
  console.log('chain fonts<12', JSON.stringify((await L.fontsUnder(page, '.tj-chain')).filter((s) => !s.includes('bx-face'))))
  await strip.first().click()
  await page.waitForTimeout(1100)
  await page.screenshot({ path: O + '02-opened.png' })
  console.log('panel', await page.locator('.sit-attpanel').count(), 'whypanel', await page.locator('.sit-whypanel').count(), 'back arrow', await page.locator('.sit-attpanel [aria-label="Back to why"]').count())
  console.log('focus on open', await L.focusDesc(page))
  console.log('strip aria now', await strip.first().evaluate((b) => [b.getAttribute('aria-expanded'), b.getAttribute('aria-controls')]))
  // Escape with held open
  await page.locator('.sit-att__heldsum').click().catch(() => {})
  await page.waitForTimeout(200)
  await page.keyboard.press('Escape')
  await page.waitForTimeout(700)
  console.log('after Escape panel', await page.locator('.sit-attpanel').count(), 'focus', await L.focusDesc(page))
  // reopen, X
  await strip.first().click()
  await page.waitForTimeout(1100)
  await page.locator('.sit-attpanel [aria-label="Close the panel"]').click()
  await page.waitForTimeout(700)
  console.log('after X panel', await page.locator('.sit-attpanel').count(), 'focus', await L.focusDesc(page))
  // reopen, narrow
  await strip.first().click()
  await page.waitForTimeout(1100)
  await page.locator('.sit-attpanel [aria-label="Narrow the panel"]').click()
  await page.waitForTimeout(600)
  await page.screenshot({ path: O + '03-narrow.png' })
  await page.locator('.sit-attpanel').screenshot({ path: O + '04-narrow-panel.png' })
  console.log('narrow overlaps', JSON.stringify(await L.overlaps(page, '.sit-attpanel'), null, 1))
  console.log('narrow clipped', JSON.stringify((await L.clipped(page, '.sit-attpanel')).filter((s) => !s.includes('u-sr-only')), null, 1))
  console.log('narrow fonts<12', JSON.stringify((await L.fontsUnder(page, '.sit-attpanel')).filter((s) => !s.includes('bx-face'))))
  const body = page.locator('.sit-attpanel .bb__inspbody')
  await body.evaluate((b) => { b.scrollTop = 400 })
  await page.waitForTimeout(200)
  await page.locator('.sit-attpanel').screenshot({ path: O + '05-narrow-scrolled.png' })
  // tab order inside a row
  await body.evaluate((b) => { b.scrollTop = 0 })
  await page.locator('.sit-attpanel h2').focus()
  const tabs = []
  for (let i = 0; i < 10; i++) { await page.keyboard.press('Tab'); tabs.push(await L.focusDesc(page)) }
  console.log('tab order', JSON.stringify(tabs, null, 1))
  // widen back
  await page.locator('.sit-attpanel [aria-label="Widen the panel"]').click()
  await page.waitForTimeout(400)
  // play a held row whose answer was stricter than asked
  await page.locator('.sit-att__heldsum').click()
  await page.waitForTimeout(300)
  const heldRows = await page.evaluate(() => [...document.querySelectorAll('.sit-att__held .sit-att__row')].map((r) => r.querySelector('.sit-att__name')?.textContent + ' :: ' + r.querySelector('.sit-att__result')?.textContent))
  console.log('held', JSON.stringify(heldRows, null, 1))
  const target = page.locator('.sit-att__held .sit-att__row').filter({ hasText: 'Contractor on an unmanaged device' }).locator('.sit-att__play')
  if (await target.count()) {
    await target.click()
    await page.waitForTimeout(14000)
    const out2 = page.locator('[data-node="outcome"]').first()
    await out2.scrollIntoViewIfNeeded()
    await out2.screenshot({ path: O + '06-held-played.png' })
    console.log('held played outcome:', (await out2.innerText()).replace(/\n/g, ' / ').slice(0, 300))
  }
  console.log(errors.length ? 'ERRORS ' + errors.join(' | ') : 'no errors')
  await browser.close()
})().catch((e) => { console.error(e); process.exit(1) })
