// s5: weaker-factor fix arrival on GitHub; GD decided-by; reduced-motion back-to-why on Maya/AWS
const L = require('./lib.cjs')
const { chromium } = require('playwright')
const O = L.OUT + 's5-'
;(async () => {
  {
    const { browser, page, errors } = await L.open()
    await L.toChecks(page)
    await L.fillAndRun(page, 'Arun', 'GitHub')
    await page.locator('button.tj-hero__strip').first().click()
    await page.waitForTimeout(1100)
    const row = page.locator('.sit-attpanel .sit-att__row.is-weaker-factor').first()
    await row.getByRole('button', { name: /Fix in policy/ }).click()
    await page.waitForTimeout(2200)
    await page.screenshot({ path: O + '01-wf-arrive.png' })
    const toast = await page.locator('.bshell__toasttext').allTextContents()
    console.log('wf toast', JSON.stringify(toast))
    const sel = await page.evaluate(() => [...document.querySelectorAll('.bb__card.is-selected')].map((e) => e.innerText.replace(/\n/g, ' / ').slice(0, 200)))
    console.log('wf selected', JSON.stringify(sel))
    console.log('wf focus', await L.focusDesc(page))
    console.log('wf unsaved', await page.getByText('Unsaved changes').count())
    // back to access checks, GD decided-by row
    await page.goBack().catch(() => {})
    console.log(errors.length ? 'ERRORS ' + errors.join(' | ') : 'no errors (wf)')
    await browser.close()
  }
  {
    const { browser, page, errors } = await L.open()
    await L.toChecks(page)
    await L.fillAndRun(page, 'Arun', 'GitHub')
    await page.locator('button.tj-hero__strip').first().click()
    await page.waitForTimeout(1100)
    const gd = page.locator('.sit-attpanel .sit-att__row.is-cant-tell .sit-att__by').first()
    console.log('gd by', await gd.innerText())
    await gd.click()
    await page.waitForTimeout(2500)
    await page.screenshot({ path: O + '02-gd-open.png' })
    console.log('gd title', await page.locator('.bb__titlebtn, .bbar__title, h1').first().innerText().catch(() => '?'))
    console.log(errors.length ? 'ERRORS ' + errors.join(' | ') : 'no errors (gd)')
    await browser.close()
  }
  {
    // reduced motion
    const browser = await chromium.launch({ channel: 'chrome', headless: true })
    const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2, reducedMotion: 'reduce' })
    await ctx.addInitScript(() => { try { localStorage.setItem('idp.board-tour.seen', '1'); localStorage.setItem('idp.tour.seen', '1') } catch {} })
    const page = await ctx.newPage()
    const errors = []
    page.on('pageerror', (e) => errors.push(String(e)))
    page.on('console', (m) => m.type() === 'error' && errors.push(m.text()))
    await page.goto((process.env.BASE || 'http://localhost:5173/'), { waitUntil: 'networkidle' })
    await L.toChecks(page)
    await L.fillAndRun(page, 'Maya Iyer', 'AWS Console', { wait: 4000 })
    await page.locator('button.tj-hero__strip').first().click()
    await page.waitForTimeout(80)
    await page.screenshot({ path: O + '03-rm-why-80ms.png' })
    await page.locator('.sit-whypanel').getByRole('button', { name: /Review attempts/ }).click()
    await page.waitForTimeout(60)
    await page.screenshot({ path: O + '04-rm-attempts-60ms.png' })
    const tr = await page.locator('.sit-attpanel').evaluate((e) => [getComputedStyle(e).transform, getComputedStyle(e).opacity])
    console.log('rm attempts transform/opacity at 60ms', JSON.stringify(tr))
    console.log('rm sides in DOM', await page.locator('.sit-panel').count())
    console.log('rm focus', await L.focusDesc(page))
    await page.locator('.sit-attpanel [aria-label="Back to why"]').click()
    await page.waitForTimeout(150)
    console.log('after back: why', await page.locator('.sit-whypanel').count(), 'att', await page.locator('.sit-attpanel').count(), 'focus', await L.focusDesc(page))
    await page.screenshot({ path: O + '05-rm-back.png' })
    await page.keyboard.press('Escape')
    await page.waitForTimeout(150)
    console.log('after Esc from why: panels', await page.locator('.sit-panel').count(), 'focus', await L.focusDesc(page))
    console.log(errors.length ? 'ERRORS ' + errors.join(' | ') : 'no errors (rm)')
    await browser.close()
  }
})().catch((e) => { console.error(e); process.exit(1) })
