const { open, pick, film, metrics, field } = require('./lib.cjs')
const OUT = process.argv[2] || require('path').join(__dirname, 'out'); require('fs').mkdirSync(OUT, { recursive: true })
;(async () => {
  const { browser, p, errs } = await open()
  await p.screenshot({ path: `${OUT}/a-empty.png` })
  await pick(p, 'Person', 'Arun')
  await pick(p, 'Application', 'GitHub')
  await p.waitForTimeout(700)
  await p.screenshot({ path: `${OUT}/b-card-app.png` })
  await field(p, 'from', 'Home broadband')
  await p.screenshot({ path: `${OUT}/b2-card-home.png` })
  await p.getByRole('button', { name: 'Run', exact: true }).click()
  const r = await film(p, `${OUT}/film`, '', 150, 60)
  console.log('film', JSON.stringify(r))
  await p.waitForTimeout(500)
  await p.screenshot({ path: `${OUT}/c-settled.png` })
  console.log('metrics', JSON.stringify(await metrics(p)))
  console.log('focus', await p.evaluate(() => document.activeElement?.outerHTML.slice(0, 120)))
  console.log('errors', errs)
  await browser.close()
})().catch((e) => { console.error(e); process.exit(1) })
