/* GENERATED by scripts/fetch-logos.mjs — do not edit by hand.
   Run `npm run logos` to refresh, `npm run logos -- --force` to refetch.
   Resolved 16 of 16 at 2026-08-13T11:22:45.209Z. */

export interface ResolvedLogo {
  id: string
  name: string
  domain: string
  /** Public path, or null when every provider failed. */
  file: string | null
  /** Which provider answered, for provenance. */
  provider: string | null
}

export const GENERATED_AT = '2026-08-13T11:22:45.209Z'

export const RESOLVED_LOGOS: Record<string, ResolvedLogo> = {
  'salesforce': { id: 'salesforce', name: "Salesforce", domain: 'salesforce.com', file: '/logos/salesforce.ico', provider: 'duckduckgo' },
  'workday': { id: 'workday', name: "Workday", domain: 'workday.com', file: '/logos/workday.ico', provider: 'duckduckgo' },
  'github': { id: 'github', name: "GitHub Enterprise", domain: 'github.com', file: '/logos/github.ico', provider: 'duckduckgo' },
  'm365': { id: 'm365', name: "Microsoft 365", domain: 'microsoft.com', file: '/logos/m365.ico', provider: 'duckduckgo' },
  'jira': { id: 'jira', name: "Jira", domain: 'atlassian.com', file: '/logos/jira.ico', provider: 'duckduckgo' },
  'slack': { id: 'slack', name: "Slack", domain: 'slack.com', file: '/logos/slack.png', provider: 'duckduckgo' },
  'aws': { id: 'aws', name: "AWS Console", domain: 'aws.amazon.com', file: '/logos/aws.ico', provider: 'duckduckgo' },
  'zoom': { id: 'zoom', name: "Zoom", domain: 'zoom.us', file: '/logos/zoom.ico', provider: 'duckduckgo' },
  'box': { id: 'box', name: "Box", domain: 'box.com', file: '/logos/box.png', provider: 'duckduckgo' },
  'servicenow': { id: 'servicenow', name: "ServiceNow", domain: 'servicenow.com', file: '/logos/servicenow.ico', provider: 'duckduckgo' },
  'okta': { id: 'okta', name: "Okta", domain: 'okta.com', file: '/logos/okta.ico', provider: 'duckduckgo' },
  'google': { id: 'google', name: "Google Workspace", domain: 'google.com', file: '/logos/google.ico', provider: 'duckduckgo' },
  'dropbox': { id: 'dropbox', name: "Dropbox", domain: 'dropbox.com', file: '/logos/dropbox.ico', provider: 'duckduckgo' },
  'zendesk': { id: 'zendesk', name: "Zendesk", domain: 'zendesk.com', file: '/logos/zendesk.ico', provider: 'duckduckgo' },
  'confluence': { id: 'confluence', name: "Confluence", domain: 'atlassian.com', file: '/logos/confluence.ico', provider: 'duckduckgo' },
  'miniorange': { id: 'miniorange', name: "miniOrange", domain: 'miniorange.com', file: '/logos/miniorange.png', provider: 'duckduckgo' },
}
