const { chromium } = require('playwright')
const OUT = require('path').join(__dirname, 'out') + '/'; require('fs').mkdirSync(OUT, { recursive: true })
;(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true })
  const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } })
  await ctx.addInitScript(() => { try { localStorage.setItem('idp.board-tour.seen', '1'); localStorage.setItem('idp.tour.seen', '1') } catch {} })
  const page = await ctx.newPage()
  await page.goto((process.env.BASE || 'http://localhost:5173/'), { waitUntil: 'networkidle' })
  await page.getByRole('button', { name: 'Check access', exact: true }).first().click()
  await page.waitForSelector('.hiw')
  await page.locator('.hiw__act button').first().click()
  await page.waitForTimeout(600)
  await page.locator('.sit-ident .bb__whorow button').first().click()
  await page.waitForTimeout(500)
  await page.getByRole('radio', { name: /Maya Iyer/ }).first().click()
  await page.getByText('Choose an application', { exact: true }).first().click()
  await page.waitForTimeout(300)
  await page.getByText('AWS Console').last().click()
  await page.waitForTimeout(400)
  await page.getByRole('button', { name: 'Run', exact: true }).click()
  await page.waitForTimeout(13000)
  const m = await page.evaluate(() => {
    const sc = document.querySelector('.tj-scroll')
    sc.scrollTop = sc.scrollHeight
    const out = document.querySelector('.tj-hero').getBoundingClientRect()
    const dock = document.querySelector('.bb__dock')?.getBoundingClientRect()
    return { outBottom: Math.round(out.bottom), dockTop: dock ? Math.round(dock.top) : null, clear: dock ? out.bottom <= dock.top : null }
  })
  await page.waitForTimeout(200)
  await page.screenshot({ path: OUT + 'dock-end.png' })
  console.log(JSON.stringify(m))
  await browser.close()
})()
