// node empty2.js <tag> [person] [app] [width] [height]
const { chromium } = require('playwright')
const OUT = require('path').join(__dirname, 'out') + '/'; require('fs').mkdirSync(OUT, { recursive: true })
const [tag = 'n', person = 'Maya Iyer', app = 'GitHub Enterprise', W = '1440', H = '900'] = process.argv.slice(2)
;(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true })
  const ctx = await browser.newContext({ viewport: { width: Number(W), height: Number(H) } })
  await ctx.addInitScript(() => { try { localStorage.setItem('idp.board-tour.seen', '1'); localStorage.setItem('idp.tour.seen', '1') } catch {} })
  const page = await ctx.newPage()
  const errors = []
  page.on('pageerror', (e) => errors.push(String(e)))
  page.on('console', (m) => m.type() === 'error' && errors.push(m.text()))
  await page.goto((process.env.BASE || 'http://localhost:5173/'), { waitUntil: 'networkidle' })
  await page.getByRole('button', { name: 'Check access', exact: true }).first().click()
  await page.waitForSelector('.hiw')
  await page.waitForTimeout(2600)
  await page.screenshot({ path: `${OUT}${tag}-1-empty.png` })
  console.log(tag, 'empty', JSON.stringify(await page.evaluate(() => ({ ways: [...document.querySelectorAll('.hiw__act button')].map((b) => b.textContent.trim()), oranges: document.querySelectorAll('.bx-btn--brand').length, scroll: (() => { const s = document.querySelector('.tj-scroll'); return s ? s.scrollHeight - s.clientHeight : null })() }))))
  await page.locator('.hiw__act button').first().click()
  await page.waitForTimeout(700)
  await page.screenshot({ path: `${OUT}${tag}-2-form.png` })
  // Choose the user through the Identity row's dialog.
  await page.locator('.sit-ident .bb__whorow button').first().click()
  await page.waitForTimeout(500)
  await page.screenshot({ path: `${OUT}${tag}-3-dialog.png` })
  await page.getByRole('radio', { name: new RegExp(person) }).first().click()
  await page.waitForTimeout(400)
  await page.getByText('Choose an application', { exact: true }).first().click()
  await page.waitForTimeout(300)
  await page.getByText(app).last().click()
  await page.waitForTimeout(600)
  await page.screenshot({ path: `${OUT}${tag}-4-filled.png` })
  console.log(tag, 'filled', JSON.stringify(await page.evaluate(() => ({ ident: document.querySelector('.sit-ident')?.textContent, sections: [...document.querySelectorAll('.sit-panel .bb__sec h3')].map((h) => h.textContent.trim()), saved: !!document.querySelector('.sit-panel__saved') }))))
  await page.getByRole('button', { name: 'Run', exact: true }).click()
  await page.waitForTimeout(Number(process.env.MID || 4200))
  await page.screenshot({ path: `${OUT}${tag}-4b-mid.png` })
  await page.waitForTimeout(9000)
  await page.screenshot({ path: `${OUT}${tag}-5-ran.png` })
  await page.evaluate(() => { const sc = document.querySelector('.tj-scroll'); if (sc) sc.scrollTop = 0 })
  await page.waitForTimeout(300)
  await page.screenshot({ path: `${OUT}${tag}-5b-top.png` })
  if (process.env.EDIT) {
    await page.locator('.tj-sin2__edit').click()
    await page.waitForTimeout(800)
    await page.screenshot({ path: `${OUT}${tag}-5c-edit.png` })
    console.log(tag, 'edit', JSON.stringify(await page.evaluate(() => ({ form: !!document.querySelector('.sit-panel .sit-ident'), focus: document.activeElement?.getAttribute('aria-label') }))))
    await page.keyboard.press('Escape')
    await page.waitForTimeout(500)
  }
  const strip = page.locator('button.tj-hero__strip')
  if (await strip.count()) {
    await strip.click()
    await page.waitForTimeout(800)
    await page.screenshot({ path: `${OUT}${tag}-6-why.png` })
    console.log(tag, 'why', JSON.stringify(await page.evaluate(() => ({ panel: !!document.querySelector('.sit-whypanel .tj-why'), title: document.querySelector('.sit-whypanel .tj-why__title')?.textContent }))))
  }
  console.log(errors.length ? 'ERRORS ' + errors.join(' | ') : 'no errors')
  await browser.close()
})().catch((e) => { console.error(e); process.exit(1) })
