async function film(rec, page) {
  const W = (ms) => rec.hold(ms * K)
  const nav = page.locator('nav')
  const leaveGuard = async () => {
    const d = page.getByRole('dialog').filter({ hasText: 'Unsaved changes' })
    if (await d.isVisible().catch(() => false)) { await rec.click(d.getByRole('button', { name: 'Discard' })); await W(500) }
  }
  /* A Policies sub-page, opening the rail and its group first when a board has collapsed them. */
  const sub = async (name) => {
    const item = nav.getByRole('button', { name, exact: true })
    if (!(await item.first().isVisible().catch(() => false))) {
      const ex = page.getByRole('button', { name: 'Expand navigation' })
      if (await ex.isVisible().catch(() => false)) { await rec.click(ex); await W(400) }
    }
    if (!(await item.first().isVisible().catch(() => false))) { await rec.click(nav.locator('button.bshell__item', { hasText: 'Policies' })); await W(400) }
    await rec.click(item)
    await leaveGuard()
    await W(500)
  }
  /* Tick a check and prove it: a landed click proves nothing, and a row at the
     list's edge takes the press somewhere else. */
  const tick = async (name) => {
    const row = page.locator('.bdpw__list [role=checkbox]', { hasText: new RegExp('^' + name + '$') }).first()
    for (let i = 0; i < 3; i++) {
      if ((await row.getAttribute('aria-checked')) === 'true') break
      await rec.click(row)
      await W(250)
    }
    if ((await row.getAttribute('aria-checked')) !== 'true') rec.problems.push('did not tick ' + name)
  }
  const insp = page.locator('.bb__insp')
  const ifHead = insp.locator('.bb__sec__head h3', { hasText: /^If$/ })
  const option = (name) => page.locator('.cp__pop .bx-menu__item, .cp__pop [role=option], [role=listbox] [role=option]', { hasText: name })
  /* A chapter opener: the card holds for as long as its line is spoken. */
  const card = async (id, html) => {
    await rec.cap('')
    rec.mark('card', { card: html })
    rec.mark('say', { id })
    rec.sayEnd = Date.now() + (rec.vo[id] ? rec.vo[id].duration : 2) * 1000
    await rec.endSay(700)
    rec.mark('card', { card: null })
    await W(400)
  }

  await page.goto(URL, { waitUntil: 'load' })
  await page.waitForSelector('main')
  await page.waitForTimeout(900)

  /* ---- 0. First look ---- */
  await card('k0', '<div class="kick">A first-time admin</div><h1>Signs in and gets to work</h1><p>Today’s prototype, recorded as it is. The panel on the right tracks the 16 use cases from the brief.</p>')
  await rec.say('c01', 'Signed in for the first time, the admin lands on <b>Policies</b>.')
  await rec.startSay('c02', 'What a rule can use sits under Policies: templates, zones, device profiles and risk signals.')
  await rec.hover(nav.getByRole('button', { name: 'Templates', exact: true })); await W(250)
  await rec.hover(nav.getByRole('button', { name: 'Zones', exact: true })); await W(250)
  await rec.hover(nav.getByRole('button', { name: 'Device profiles', exact: true })); await W(250)
  await rec.hover(nav.getByRole('button', { name: 'Risk signal profile', exact: true }))
  await rec.endSay()

  /* ---- 1. Device health ---- */
  await card('k1', chapter(1, 'Device health', 'Build a Device health profile from scratch, then a policy that uses it.', [1, 2, 3, 4, 9]))
  await rec.startSay('c03', '<b>Device profiles</b>: checks a device must pass, or signals that recognise it.')
  await sub('Device profiles')
  await rec.endSay()
  await rec.startSay('c04', 'A new profile starts with a name.')
  await rec.click(page.getByRole('button', { name: /Create new profile/ }))
  await rec.type(page.locator('main input').first(), 'Company devices')
  await rec.endSay()
  await rec.startSay('c05', 'The type: <b>Device health</b>, checks a device must pass at sign-in.')
  await rec.click(page.locator('main [role=radio]', { hasText: 'Device health' }))
  await rec.endSay()
  await rec.click(page.getByRole('button', { name: 'Next', exact: true })); await W(800)
  await rec.expect(page.locator('.bdpw__list'), 'the checks list')

  rec.focus(F[1])
  await rec.startSay('c06', '<b>#1</b> A minimum OS version per platform — and no “warn” answer: only Allow or Deny.')
  await tick('Windows')
  await rec.click(page.getByRole('combobox', { name: 'Minimum Windows version' }))
  await rec.click(page.getByRole('option', { name: 'Windows 11', exact: true }))
  await tick('Android')
  await rec.endSay()
  rec.focus(F[2])
  await rec.startSay('c07', '<b>#2</b> Device integrity: not rooted, jailbroken or tampered with.')
  await tick('Device integrity')
  await rec.endSay()
  rec.focus(F[3])
  await rec.startSay('c08', '<b>#3</b> A screen lock must be set.')
  await tick('Screen lock')
  await rec.endSay()
  rec.focus(F[4])
  await rec.startSay('c09', '<b>#4</b> The lowest miniOrange Authenticator version allowed.')
  await tick('miniOrange Authenticator')
  await rec.endSay()
  rec.focus(F[9])
  await rec.startSay('c10', '<b>#9</b> And a minimum browser version.')
  await tick('Chrome')
  await rec.endSay()
  await rec.startSay('c11', 'Every version is a minimum; the column heading says so once.')
  await rec.hover(page.locator('.bdpw__colhead .bfp2__colnote').first())
  await rec.endSay()
  await rec.startSay('c12', 'Review, then create.')
  await rec.click(page.getByRole('button', { name: 'Next', exact: true })); await W(900)
  await rec.endSay()
  await rec.startSay('c13', 'Created. Now a policy that uses it.')
  await rec.click(page.getByRole('button', { name: 'Create profile' }))
  await rec.expect(page.getByText('Company devices created'), 'the created toast')
  await rec.endSay()
  await sub('All Policies')
  await rec.startSay('c14', 'Name the policy, and pick the application it protects.')
  await rec.click(page.getByRole('button', { name: /New policy/ }))
  await rec.type(page.locator('#np-name'), 'Company devices only')
  await rec.click(page.getByRole('combobox', { name: 'Applications this policy protects' }))
  await rec.click(page.getByRole('option', { name: /^Salesforce/ }))
  await rec.click(page.getByRole('dialog').locator('h2').first())
  await rec.endSay()
  await rec.startSay('c15', 'A new policy starts empty: a template, or the first rule by hand.')
  await rec.click(page.getByRole('button', { name: 'Create policy' })); await W(1100)
  await rec.endSay()
  await rec.click(page.getByRole('button', { name: /Start from scratch/ })); await W(600)
  await rec.click(page.getByRole('button', { name: 'Add the first rule' })); await W(900)
  await rec.expect(insp, 'the rule panel')
  await rec.startSay('c16', 'If the device <b>does not match</b> Company devices…')
  await rec.type(insp.getByRole('textbox', { name: 'Rule name' }), 'Not a company device', { clear: true })
  await rec.click(insp.getByRole('button', { name: 'Add condition', exact: true }))
  await rec.click(page.locator('.bx-menu__item', { hasText: 'Device profile' }).first()); await W(400)
  await rec.click(option('does not match').first()); await W(400)
  await rec.click(option('Company devices').last()); await W(300)
  await rec.click(ifHead)
  rec.focus(F.rule)
  await rec.endSay()
  await rec.startSay('c17', '…then <b>Deny</b>, with a message. Allow or Deny are the only answers: there is no warn.')
  await rec.click(insp.locator('button', { hasText: /^Deny/ }))
  await rec.type(insp.locator('textarea'), 'Use a company device that meets our health checks.', { delay: 26 })
  await rec.hover(insp.locator('.bb__outcard.is-soon')).catch(() => {})
  await rec.endSay()
  await rec.startSay('c18', 'Review, then turn it on.')
  await rec.click(page.getByRole('button', { name: 'Review & save' })); await W(800)
  await rec.endSay()
  await rec.startSay('c19', 'Saved and on. To see it work a first-timer would try a sign-in, and <b>this build has no way to</b>.')
  await rec.click(page.getByRole('button', { name: 'Save and turn on' })); await W(1200)
  await rec.endSay()

  /* ---- 2. Risk ---- */
  await card('k2', chapter(2, 'Risk', 'Where the Device risk score comes from, and a rule that steps up when it is high.', [5, 7]))
  await sub('Risk signal profile')
  rec.focus(F[5])
  await rec.startSay('c20', '<b>#5</b> Mobile SDK signals, each with one priority, make up the <b>Device risk score</b>.')
  await rec.click(page.getByRole('button', { name: 'Shipped priorities', exact: true })); await W(1100)
  await rec.wheel(420)
  await rec.endSay()
  await rec.say('c21', 'Device health does not feed this score: a health check is only pass or fail.')
  await sub('All Policies')
  await rec.startSay('c22', 'Back in the policy, a second rule for a risky device.')
  await rec.click(page.getByRole('button', { name: 'Company devices only', exact: true })); await W(1300)
  await rec.click(page.getByRole('button', { name: 'Add a rule at the end' })); await W(900)
  await rec.type(insp.getByRole('textbox', { name: 'Rule name' }), 'Risky device', { clear: true })
  await rec.endSay()
  rec.focus(F[7])
  await rec.startSay('c23', '<b>#7</b> If the Device risk score is above 69…')
  await rec.click(insp.getByRole('button', { name: 'Add condition', exact: true }))
  await rec.click(page.locator('.bx-menu__item', { hasText: 'Device risk score' }).first()); await W(400)
  await rec.click(option('above').first()); await W(300)
  await rec.type(insp.getByRole('spinbutton', { name: 'Device risk score' }).or(insp.getByRole('textbox', { name: 'Device risk score' })), '69', { clear: true })
  await rec.click(ifHead)
  await rec.endSay()
  await rec.startSay('c24', '…allow, but ask for a <b>second factor</b>. Rules run top to bottom, and the first match wins.')
  await rec.click(insp.locator('button', { hasText: /^Allow/ })); await W(400)
  await rec.click(insp.getByRole('combobox', { name: 'Second factor' }))
  await rec.click(page.getByRole('option', { name: /^Any enabled method/ }))
  await rec.endSay()
  await rec.startSay('c25', '“A stronger method” is a hand-picked list here: there is no phishing-resistant choice.')
  await rec.click(page.getByRole('button', { name: 'Review & save' })); await W(800)
  await rec.click(page.getByRole('dialog').getByRole('button', { name: /Save changes|Save and turn on/ })); await W(1100)
  await rec.endSay()

  /* ---- 3. Templates, copies, trying first ---- */
  await card('k3', chapter(3, 'Templates, copies, and trying before enforcing', 'Start from a template, copy a policy, and look for a way to see its effect first.', [11, 6]))
  await sub('Templates')
  rec.focus(F[11])
  await rec.startSay('c26', '<b>#11</b> Twelve ready-made templates, including the two in the brief.')
  await rec.hover(page.getByRole('button', { name: 'Use Require MFA for all users' })); await W(900)
  await rec.hover(page.getByRole('button', { name: 'Use Block access outside office network' }))
  await rec.endSay()
  await rec.startSay('c27', 'The template’s rules land on the board, ready to edit.')
  await rec.click(page.getByRole('button', { name: 'Use Require MFA for all users' })); await W(600)
  const dlg = page.getByRole('dialog')
  await rec.type(dlg.locator('input').first(), 'MFA for everyone')
  await rec.click(dlg.getByRole('combobox', { name: 'Applications this policy protects' }))
  await rec.click(page.getByRole('option', { name: /^Slack/ }))
  await rec.click(dlg.locator('h2').first())
  await rec.click(dlg.getByRole('button', { name: 'Create policy' })); await W(1300)
  await rec.endSay()
  await rec.startSay('c28', 'Any policy can be copied from its row menu, or saved as a template.')
  await rec.click(page.getByRole('button', { name: 'Back to policies' })); await leaveGuard(); await W(900)
  await rec.click(page.getByRole('button', { name: 'Actions for Company devices only' })); await W(600)
  await rec.hover(page.getByRole('menuitem', { name: 'Save as template' }))
  await rec.endSay()
  await rec.startSay('c29', '<b>Duplicate</b> opens the copy as a draft. There is no “Save as” inside the builder.')
  await rec.click(page.getByRole('menuitem', { name: 'Duplicate' })); await W(1300)
  await rec.endSay()
  await rec.click(page.getByRole('button', { name: 'Back to policies' })); await leaveGuard(); await W(900)
  rec.focus(F[6])
  await rec.startSay('c30', '<b>#6</b> What a first-timer can’t do: see what a policy <b>would have done</b> before it is on.')
  await rec.hover(page.getByRole('button', { name: 'Draft', exact: true })); await W(700)
  await rec.hover(page.getByRole('button', { name: 'Inactive', exact: true }))
  await rec.endSay()
  await rec.say('c31', 'Draft and Inactive decide nothing and record nothing. There is no report-only mode.')

  /* ---- 4. Zones and trusted devices ---- */
  await card('k4', chapter(4, 'Zones and trusted devices', 'Build a zone, then look at how a device can be recognised.', [12, 8]))
  await sub('Zones')
  rec.focus(F[12])
  await rec.startSay('c32', '<b>#12</b> A zone holds IP networks…')
  await rec.click(page.getByRole('button', { name: /New zone/ }).first()); await W(400)
  await rec.type(page.getByRole('dialog').locator('input').first(), 'Pune office')
  await rec.click(page.getByRole('button', { name: 'Continue' })); await W(800)
  await rec.click(page.getByRole('button', { name: 'Add IP' }).first())
  await rec.type(page.getByRole('textbox', { name: 'IP address, network or ASN' }), '203.0.113.0/24')
  await rec.endSay()
  await rec.startSay('c33', '…and places: a country, a state, or a city with a range around it.')
  await rec.click(page.getByRole('tab', { name: 'Locations' })); await W(400)
  await rec.click(page.getByRole('button', { name: 'Add location' }))
  await page.keyboard.type('Pune', { delay: 70 }); await W(600)
  await rec.click(page.getByRole('option', { name: /Pune/ }).first()); await W(500)
  await rec.type(page.getByRole('spinbutton', { name: 'Range around Pune' }), '25', { clear: true })
  await rec.endSay()
  await rec.startSay('c34', 'Saved, and ready for any rule, but built here, away from the policy that needs it.')
  await rec.click(page.getByRole('button', { name: 'Review & save' })); await W(700)
  await rec.click(page.getByRole('button', { name: 'Create zone' })); await W(1100)
  await rec.endSay()
  await sub('Device profiles')
  await rec.startSay('c35', 'A <b>Trusted device</b> profile recognises machines it has seen before.')
  await rec.click(page.getByRole('button', { name: /Create new profile/ }))
  await rec.type(page.locator('main input').first(), 'Office laptops')
  await rec.click(page.locator('main [role=radio]', { hasText: 'Trusted device' }))
  await rec.endSay()
  rec.focus(F[8])
  await rec.startSay('c36', '<b>#8</b> Agentless reads the browser, network and location; <b>Agent-based</b> adds hardware identifiers…')
  await rec.click(page.getByRole('button', { name: 'Next', exact: true })); await W(900)
  await rec.click(page.locator('main [role=radio]', { hasText: 'Agent-based' }))
  await rec.endSay()
  await rec.say('c37', '…but the Device Agent is Windows only, and there is no one agent for MFA and adaptive.')
  await rec.click(page.getByRole('button', { name: 'All profiles' })); await leaveGuard(); await W(700)
  await rec.startSay('c38', 'Devices › <b>MFA Agents</b> is marked Coming soon.')
  await rec.click(nav.locator('button.bshell__item', { hasText: 'Devices' })); await W(400)
  await rec.hover(nav.getByRole('button', { name: 'MFA Agents', exact: true }))
  await rec.endSay()

  /* ---- 5. Not built yet ---- */
  await card('k5', chapter(5, 'Not built yet', 'The admin dashboard, UEM, registration review and plain-language setup.', [10, 13, 14, 15, 16]))
  rec.focus(F[10])
  await rec.startSay('c39', '<b>#10</b> Step-up for the admin dashboard: <b>Setup 2FA for Admin</b> is Coming soon.')
  await rec.click(nav.locator('button.bshell__item', { hasText: 'Authentication methods' }).first()); await W(400)
  await rec.hover(nav.getByRole('button', { name: 'Setup 2FA for Admin', exact: true }))
  await rec.endSay()
  rec.focus(F[1315])
  await rec.startSay('c40', '<b>#13, #15</b> The only way in for outside systems is a generic external hook: no UEM, no posture checks.')
  await sub('External Hooks')
  await rec.endSay()
  rec.focus(F[14])
  await rec.startSay('c41', '<b>#14</b> A new 2FA method is simply added: nothing flags, holds or reviews a suspicious one.')
  await sub('Authentication methods')
  await rec.endSay()
  rec.focus(F[16])
  await rec.startSay('c42', '<b>#16</b> Every policy is built by hand: there is no way to describe one in a sentence.')
  await sub('All Policies')
  await rec.click(page.getByRole('button', { name: /New policy/ })); await W(800)
  await rec.endSay()
  await rec.click(page.getByRole('dialog').getByRole('button', { name: 'Cancel' })); await W(500)
  await rec.cap(''); await W(500)
}

