import { createRequire } from 'node:module'
const V=decodeURIComponent(new URL('../../../../video', import.meta.url).pathname).replace(/^\/(\w:)/, '$1')
const require=createRequire(`file:///${V.replace(/ /g,'%20')}/package.json`)
const {chromium}=require('playwright')
const b=await chromium.launch({channel:'chrome',headless:true})
const c=await b.newContext({viewport:{width:1440,height:810}})
await c.addInitScript(()=>{try{localStorage.setItem('idp.board-tour.seen','1')}catch{}})
const p=await c.newPage()
const btn=(re)=>p.getByRole('button',{name:re}).first()
const ifsec=async(l)=>console.log('\n'+l+'\n'+(await p.$$eval('.bb__sec', e=>{const s=e.find(x=>/^\s*If/.test(x.textContent));return s?[...s.querySelectorAll('button')].map(b=>`  ${(typeof b.className==='string'?b.className:'').split(' ')[0]} :: ${(b.getAttribute('aria-label')||b.textContent||'').trim().slice(0,40)} :: vis=${b.getClientRects().length>0}`):['(no If section)']})).join('\n'))
await p.goto('http://localhost:5173/',{waitUntil:'networkidle'}); await p.waitForTimeout(800)
await btn(/^New policy$/).click(); await p.waitForTimeout(1100)
await btn(/Start from scratch/).click(); await p.waitForTimeout(700)
await p.locator('.bb__link__add').first().click(); await p.waitForTimeout(900)
await ifsec('BEFORE ANY CONDITION')
await p.locator('.bb__ifadd').filter({hasText:'Add condition'}).first().click(); await p.waitForTimeout(600)
await p.getByRole('option',{name:/Device profile/}).first().click(); await p.waitForTimeout(700)
await p.locator('.cp__fld').last().click(); await p.waitForTimeout(700)
await p.locator('[role=checkbox]').filter({hasText:/Corporate managed/}).first().click(); await p.waitForTimeout(500)
await p.keyboard.press('Escape'); await p.waitForTimeout(600)
await ifsec('AFTER ONE CONDITION')
const addBtn = p.locator('.bb__sec').filter({hasText:/^\s*If/}).locator('.bx-btn').filter({hasText:/^Add$/}).first()
console.log('add btn count', await addBtn.count())
await addBtn.click(); await p.waitForTimeout(700)
console.log('MENU:', await p.$$eval('[role=option],[role=menuitem],.bx-menu__item', e=>e.filter(x=>x.getClientRects().length>0).map(x=>`${x.tagName}(${x.getAttribute('role')||''}) ${(x.getAttribute('aria-label')||x.textContent||'').trim().slice(0,40)}`)))
await b.close()
